server:
  port: 8080
  error:
    include-message: always
    include-binding-errors: always

spring:
  profiles:
    active: ${SPRING_PROFILE}
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  security:
    user:
      name: ${SPRING_SECURITY_USER}
      password: ${SPRING_SECURITY_PASSWORD}

jwt:
  token-issuer: ${JWT_ISSUER}
  token-signing-key: ${JWT_SIGNING_KEY}
  token-duration: ${JWT_DURATION}
