server:
  port: 8080

spring:
  profiles:
    active: ${SPRING_PROFILE}
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  security:
    user:
      name: ${SPRING_SECURITY_USER}
      password: ${SPRING_SECURITY_PASSWORD}
  cache:
    jcache:
      config: classpath:ehcache.xml

jwt:
  issuer: ${JWT_ISSUER}
  signing-key: ${JWT_SIGNING_KEY}
  duration-minutes: ${JWT_DURATION_MINUTES}
  leeway-seconds: ${JWT_LEEWAY_SECONDS}

springdoc:
  default-produces-media-type: application/json

bucket4j:
  enabled: true
  filters:
    - cache-name: bucket4j-buckets
      url: /sign-in
      http-response-body: ''
      rate-limits:
        - expression: getRemoteAddr()
          bandwidths:
            - capacity: 1
              time: 500
              unit: millis
              fixed-refill-interval: 1
              fixed-refill-interval-unit: minutes
    - cache-name: bucket4j-buckets
      url: /sign-up
      http-response-body: ''
      rate-limits:
        - expression: getRemoteAddr()
          bandwidths:
            - capacity: 1
              time: 500
              unit: millis
              fixed-refill-interval: 1
              fixed-refill-interval-unit: minutes
