scrape_configs:

  - job_name: to-do-list
    scrape_interval: 2s
    metrics_path: /actuator/prometheus
    static_configs:
      - targets:
          - app:8081
        labels:
          application: to-do-list
