apiVersion: v1

kind: PersistentVolume

metadata:
  name: grafana-pv
  labels:
    app: grafana
    type: local

spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/data/grafana
