apiVersion: v1

kind: Service

metadata:
  name: grafana
  labels:
    app: grafana

spec:
  type: NodePort
  ports:
    - name: 3000-3000
      port: 3000
      targetPort: 3000
  selector:
    app: grafana
