apiVersion: v1

kind: PersistentVolumeClaim

metadata:
  name: grafana-pvc
  labels:
    app: grafana

spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
