apiVersion: v1
kind: Secret
metadata:
  name: app-secret
  labels:
    app: to-do-list
type: Opaque
data:
  POSTGRES_USER: aHU1NTNpbg==
  POSTGRES_PASSWORD: TWlVYjIyNkRNQjh0YUFlZQ==
  SPRING_SECURITY_USER: aHU1NTNpbg==
  SPRING_SECURITY_PASSWORD: M3B1UW1mRlNBa2lUZVh0eA==
  JWT_ISSUER: aHU1NTNpbg==
  JWT_SIGNING_KEY: NTdhOTVmYzdkNGUxZWFjNDJkY2MyMWU5M2NhMjEyNzI0MjU0YzRmMDE2NDQ4YWVjNzg2ODI1YzVkYzMxYWYyOQ==
