apiVersion: apps/v1

kind: Deployment

metadata:
  name: app
  labels:
    app: app

spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      initContainers:
        - name: wait-for-postgresql
          image: postgres:14-alpine
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: app-config
            - secretRef:
                name: app-secret
          command: [ '/bin/bash',
                     '-c',
                     'until pg_isready -h $POSTGRES_HOST -U $POSTGRES_USER; do echo "Retrying in 10 sec..." && sleep 10; done' ]
      containers:
        - name: app
          image: hu553in/to-do-list
          ports:
            - containerPort: 8080
            - containerPort: 8081
          envFrom:
            - configMapRef:
                name: app-config
            - secretRef:
                name: app-secret
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8081
            initialDelaySeconds: 45
            timeoutSeconds: 3
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8081
            initialDelaySeconds: 45
            timeoutSeconds: 3
