apiVersion: v1

kind: Service

metadata:
  name: postgresql
  labels:
    app: postgresql

spec:
  type: NodePort
  ports:
    - name: 5432-5432
      port: 5432
      targetPort: 5432
  selector:
    app: postgresql
