name: Gradle build
on: [push]
jobs:

  build:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin

      - name: Execute Gradle build
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 7.4.2
          arguments: build
